const About = () => {
  return (
    <div>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
      <p>THIS IS THE ABOUT SECTION</p>
    </div>
  );
};

export default About;
